baseURL: https://Philipshrimp.github.io

languageCode: en-us
title: "Vision Shrimp"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
  - HTML
  - RSS
  - JSON

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: "images/bg.jpg"

  # GitHub repo URL and branch of your site
  gitRepo: https://github.com/Philipshrimp/Philipshrimp.github.io
  gitBranch: main

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify whether you want the language flags to be displayed. 
  showFlags: true

  darkMode:
    provider: darkreader
    enable: true
    default: system

  # Provide newsletter configuration. 
  # This feature has been implemented for Mailchimp only for now.
  # You can also hide it from the footer.
  newsletter:
    # specify whether you want to display the newsletter form 
    enable: false

  # comment
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        email: true
    comment:
      enable: true
      disqus:
        shortName: philip

# robots.txt
enableRobotsTXT: true

# sitemap 생성
sitemap:
# always, hourly daily, weekly, monthly, yearly, never
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5
